spring:
  servlet:
    multipart:
      # 设置文件大小限制，超出设置页面会抛出异常信息
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/file_manage?characterEncoding=UTF-8&useUnicode=true&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useCursorFetch=true
    username: root
    password: mag5TTnZdT
    druid:
      initialSize: 2
      minIdle: 2
      maxActive: 30
      validationQuery: select 'x'
      test-on-borrow: true
server:
  # 服务端口
  port: 10040



#  文件上传路径
fileURL: /data/file/